#!/usr/bin/env python3
"""
Second data pipeline: DeepMind's OPFData, native.

This sits alongside the pandapower pipeline (`main_datagen_opf_snapshot_envelope.py`
plus the PPC branch-row parquet loader) and does not replace it. The two differ
in almost every respect except the task:

                    pandapower pipeline            OPFData pipeline
  scenarios         sampled here from CGMES        pre-generated by DeepMind
                    snapshot envelopes             from PGLib base cases
  perturbation      coupled load scaling           independent per-load, ~+/-20%
                    (measured r = +0.835)          (measured r = -0.001),
                                                   optional N-1 topology
  solver            pandapower PIPS                PowerModels / IPOPT
  format            PPC branch-row parquet         PyG HeteroData
  adapters needed   three (one per model)          one (GridFM only)
  decision space    reconstructed, limits          native and exact
                    from an empirical envelope
  supervision       bus voltages                   bus voltages, generator
                                                   dispatch, branch flows,
                                                   objective value
  grids             case14/118/300, SimBench,      10 PGLib scenarios,
                    LVN Heo1 (real CGMES)          14 to 13,659 buses

The point of the second pipeline is that **LUMINA and GridSFM consume OPFData
natively**, so their results no longer depend on adapters written here. Only
GridFM needs translating. case14 and case118 exist in both pipelines, which
makes a controlled comparison of the two generation methodologies possible.

Y-bus is rebuilt from `edge_attr` because the residual metrics need it. Verified
against OPFData's own stored solution: max|dP| = 1.3e-6 pu, which is the
tolerance of the solver that produced the data.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
from torch_geometric.data import Batch, HeteroData

# Column layouts, confirmed empirically against pglib_opf_case14_ieee.
AC_LINE = {"angmin": 0, "angmax": 1, "b_fr": 2, "b_to": 3, "r": 4, "x": 5, "rate_a": 6}
TRAFO = {"angmin": 0, "angmax": 1, "r": 2, "x": 3, "rate_a": 4, "tap": 7, "shift": 8,
         "b_fr": 9, "b_to": 10}
# generator.x: mbase, pg, pmin, pmax, qg, qmin, qmax, vg, cost_sq, cost_lin, cost_off
GEN = {"mbase": 0, "pg": 1, "pmin": 2, "pmax": 3, "qg": 4, "qmin": 5, "qmax": 6,
       "vg": 7, "c2": 8, "c1": 9, "c0": 10}
BUS = {"base_kv": 0, "bus_type": 1, "vmin": 2, "vmax": 3}


def build_ybus(data: HeteroData, dtype=torch.complex128) -> torch.Tensor:
    """Dense per-unit Y-bus from OPFData edge attributes and shunts."""
    n = int(data["bus"].x.shape[0])
    Y = torch.zeros((n, n), dtype=dtype)

    def stamp(key, cols, is_trafo):
        if key not in data.edge_types:
            return
        store = data[key]
        ei = store.edge_index
        ea = getattr(store, "edge_attr", None)
        if ea is None or ei.numel() == 0:
            return
        f = ei[0].tolist(); t = ei[1].tolist()
        a = ea.to(torch.float64)
        for k in range(len(f)):
            r = float(a[k, cols["r"]]); x = float(a[k, cols["x"]])
            b_fr = float(a[k, cols["b_fr"]]); b_to = float(a[k, cols["b_to"]])
            if is_trafo:
                tap = float(a[k, cols["tap"]]) or 1.0
                shift = float(a[k, cols["shift"]])
            else:
                tap, shift = 1.0, 0.0
            ys = 1.0 / complex(r, x) if (r or x) else 0j
            tp = tap * np.exp(1j * shift)
            i, j = int(f[k]), int(t[k])
            Y[i, i] += torch.as_tensor((ys + 1j * b_fr) / (abs(tp) ** 2), dtype=dtype)
            Y[j, j] += torch.as_tensor(ys + 1j * b_to, dtype=dtype)
            Y[i, j] += torch.as_tensor(-ys / np.conj(tp), dtype=dtype)
            Y[j, i] += torch.as_tensor(-ys / tp, dtype=dtype)

    stamp(("bus", "ac_line", "bus"), AC_LINE, False)
    stamp(("bus", "transformer", "bus"), TRAFO, True)

    if "shunt" in data.node_types and data["shunt"].x.numel():
        sx = data["shunt"].x.to(torch.float64)
        sb = data["shunt", "shunt_link", "bus"].edge_index[1].tolist()
        for k, b in enumerate(sb):
            # shunt.x = [bs, gs]
            Y[int(b), int(b)] += torch.as_tensor(complex(float(sx[k, 1]), float(sx[k, 0])), dtype=dtype)
    return Y


def _scatter_to_bus(values: torch.Tensor, bus_idx: torch.Tensor, n: int) -> torch.Tensor:
    out = torch.zeros(n, dtype=values.dtype)
    out.index_add_(0, bus_idx.to(torch.long), values)
    return out


def graph_tensors(data: HeteroData) -> Dict[str, torch.Tensor]:
    """Per-graph quantities the OPF metrics need, in per-unit."""
    n = int(data["bus"].x.shape[0])
    bus_x = data["bus"].x.to(torch.float64)

    load_bus = data["load", "load_link", "bus"].edge_index[1]
    lx = data["load"].x.to(torch.float64)
    S_load = torch.complex(
        -_scatter_to_bus(lx[:, 0], load_bus, n),
        -_scatter_to_bus(lx[:, 1], load_bus, n),
    )

    gen_bus = data["generator", "generator_link", "bus"].edge_index[1]
    gx = data["generator"].x.to(torch.float64)
    p_min = _scatter_to_bus(gx[:, GEN["pmin"]], gen_bus, n)
    p_max = _scatter_to_bus(gx[:, GEN["pmax"]], gen_bus, n)
    q_min = _scatter_to_bus(gx[:, GEN["qmin"]], gen_bus, n)
    q_max = _scatter_to_bus(gx[:, GEN["qmax"]], gen_bus, n)
    c1 = _scatter_to_bus(gx[:, GEN["c1"]], gen_bus, n)
    c2 = _scatter_to_bus(gx[:, GEN["c2"]], gen_bus, n)
    ctrl = torch.zeros(n, dtype=torch.bool)
    ctrl[gen_bus.to(torch.long)] = True

    va, vm = data["bus"].y[:, 0].to(torch.float64), data["bus"].y[:, 1].to(torch.float64)
    V_target = torch.stack([vm, va], dim=-1)
    # Flat start: 1.0 pu at zero angle, the convention the PPC pipeline uses.
    V_start = torch.stack([torch.ones(n, dtype=torch.float64),
                           torch.zeros(n, dtype=torch.float64)], dim=-1)

    gy = getattr(data["generator"], "y", None)
    S_gen = None
    if gy is not None:
        gy = gy.to(torch.float64)
        S_gen = torch.complex(_scatter_to_bus(gy[:, 0], gen_bus, n),
                              _scatter_to_bus(gy[:, 1], gen_bus, n))

    return {
        "n": n,
        "Ybus": build_ybus(data),
        "S_load": S_load,
        "S_gen": S_gen,
        "V_newton": V_target,
        "V_start": V_start,
        "bus_type": bus_x[:, BUS["bus_type"]].to(torch.long),
        "vn_kv": bus_x[:, BUS["base_kv"]],
        "Bus_vmin": bus_x[:, BUS["vmin"]],
        "Bus_vmax": bus_x[:, BUS["vmax"]],
        "Gen_p_min": p_min, "Gen_p_max": p_max,
        "Gen_q_min": q_min, "Gen_q_max": q_max,
        "Gen_cost_c1": c1, "Gen_cost_c2": c2,
        "Gen_controllable": ctrl,
        "objective": float(getattr(data, "objective", float("nan"))),
    }


def collate_opfdata(items: List[HeteroData]) -> Dict[str, torch.Tensor]:
    """Block-diagonal batch matching the PPC pipeline's conventions.

    Keeps the PyG `Batch` under "hetero" so LUMINA and GridSFM can be fed their
    native input, while the block-diagonal tensors drive the shared metrics.
    """
    per = [graph_tensors(d) for d in items]
    sizes = torch.tensor([p["n"] for p in per], dtype=torch.long)
    total = int(sizes.sum())

    Y = torch.zeros((total, total), dtype=torch.complex128)
    off = 0
    for p in per:
        n = p["n"]
        Y[off:off + n, off:off + n] = p["Ybus"]
        off += n

    def cat(key):
        return torch.cat([p[key] for p in per], dim=0)

    out = {
        "hetero": Batch.from_data_list(items),
        "sizes": sizes,
        "Ybus": Y.unsqueeze(0),
        "S_start": cat("S_load").unsqueeze(0),
        "S_load": cat("S_load").unsqueeze(0),
        "V_newton": cat("V_newton").unsqueeze(0),
        "V_start": cat("V_start").unsqueeze(0),
        "bus_type": cat("bus_type").unsqueeze(0),
        "vn_kv": cat("vn_kv").unsqueeze(0),
        "Bus_vmin": cat("Bus_vmin").unsqueeze(0),
        "Bus_vmax": cat("Bus_vmax").unsqueeze(0),
        "Gen_p_min": cat("Gen_p_min").unsqueeze(0),
        "Gen_p_max": cat("Gen_p_max").unsqueeze(0),
        "Gen_q_min": cat("Gen_q_min").unsqueeze(0),
        "Gen_q_max": cat("Gen_q_max").unsqueeze(0),
        "Gen_cost_c1": cat("Gen_cost_c1").unsqueeze(0),
        "Gen_cost_c2": cat("Gen_cost_c2").unsqueeze(0),
        "Gen_controllable": cat("Gen_controllable").to(torch.long).unsqueeze(0),
        "objective": torch.tensor([p["objective"] for p in per], dtype=torch.float64),
    }
    if per[0]["S_gen"] is not None:
        out["S_gen_opf"] = cat("S_gen").unsqueeze(0)
    # OPFData is already per-unit on the case base, so limits need no rescaling
    # (S_base = 1) and the cost coefficients are already per-unit (cost_scale = 1).
    out["S_base"] = torch.ones(len(per), dtype=torch.float64)
    out["cost_scale"] = torch.ones(len(per), dtype=torch.float64)[0]
    return out


def make_opfdata_loaders(root: str, case_name: str, batch_size: int,
                         num_groups: int = 1, topological_perturbations: bool = False,
                         max_train: int = 0, max_valid: int = 0, max_test: int = 0,
                         num_workers: int = 0):
    """train/val/test loaders over OPFData's own splits."""
    from torch.utils.data import DataLoader, Subset
    from torch_geometric.datasets import OPFDataset

    def build(split, cap):
        ds = OPFDataset(root, case_name=case_name, split=split, num_groups=num_groups,
                        topological_perturbations=topological_perturbations)
        if cap and cap < len(ds):
            ds = Subset(ds, list(range(cap)))
        return ds

    tr, va, te = build("train", max_train), build("val", max_valid), build("test", max_test)
    mk = lambda d, sh: DataLoader(d, batch_size=batch_size, shuffle=sh,
                                  collate_fn=collate_opfdata, num_workers=num_workers)
    return mk(tr, True), mk(tr, False), mk(va, False), mk(te, False)


# --------------------------------------------------------------------------- #
# GridFM adapter (the only model without native OPFData support)
# --------------------------------------------------------------------------- #

def to_gridfm_inputs(batch: Dict[str, torch.Tensor], device, feature_transform="signed_log"):
    """OPFData batch -> GridFM's bus/gen feature layout."""
    from train_valid_test_gridfm import (
        PD_H, QD_H, QG_H, VM_H, VA_H, PQ_H, PV_H, REF_H, MIN_VM_H, MAX_VM_H,
        MIN_QG_H, MAX_QG_H, GS, BS, VN_KV, PG_H, MIN_PG, MAX_PG, C1_H, G_ON,
        signed_log1p, make_branch_edge_features,
    )
    S = batch["S_start"].squeeze(0).to(device)
    bt = batch["bus_type"].squeeze(0).to(device)
    n = S.shape[0]
    x_bus = torch.zeros((n, 15), dtype=torch.float32, device=device)
    p_in, q_in = -S.real.float(), -S.imag.float()
    if feature_transform == "signed_log":
        p_in, q_in = signed_log1p(p_in), signed_log1p(q_in)
    x_bus[:, PD_H] = p_in
    x_bus[:, QD_H] = q_in
    x_bus[:, VM_H] = batch["V_start"].squeeze(0)[:, 0].float().to(device)
    x_bus[:, VA_H] = batch["V_start"].squeeze(0)[:, 1].float().to(device)
    # OPFData bus_type follows MATPOWER: 1=PQ, 2=PV, 3=ref
    x_bus[:, PQ_H] = (bt == 1).float()
    x_bus[:, PV_H] = (bt == 2).float()
    x_bus[:, REF_H] = (bt == 3).float()
    x_bus[:, MIN_VM_H] = batch["Bus_vmin"].squeeze(0).float().to(device)
    x_bus[:, MAX_VM_H] = batch["Bus_vmax"].squeeze(0).float().to(device)
    x_bus[:, MIN_QG_H] = batch["Gen_q_min"].squeeze(0).float().to(device)
    x_bus[:, MAX_QG_H] = batch["Gen_q_max"].squeeze(0).float().to(device)
    x_bus[:, VN_KV] = torch.log10(batch["vn_kv"].squeeze(0).float().to(device) + 1e-9)

    # Index the (CPU) batch tensors with a CPU index, then move: mixing a CUDA
    # index with a CPU tensor raises "indices should be either on cpu or on the
    # same device as the indexed tensor".
    ctrl_cpu = batch["Gen_controllable"].squeeze(0) > 0
    gen_bus_cpu = torch.where(ctrl_cpu)[0]
    if gen_bus_cpu.numel() == 0:
        gen_bus_cpu = torch.tensor([0], dtype=torch.long)
    gen_bus = gen_bus_cpu.to(device)
    x_gen = torch.zeros((gen_bus_cpu.numel(), 7), dtype=torch.float32, device=device)
    x_gen[:, MIN_PG] = batch["Gen_p_min"].squeeze(0)[gen_bus_cpu].float().to(device)
    x_gen[:, MAX_PG] = batch["Gen_p_max"].squeeze(0)[gen_bus_cpu].float().to(device)
    x_gen[:, C1_H] = batch["Gen_cost_c1"].squeeze(0)[gen_bus_cpu].float().to(device)
    x_gen[:, G_ON] = 1.0

    edge_bus, edge_attr_bus = gridfm_branch_edges(batch, device, feature_transform)
    gi = torch.arange(gen_bus_cpu.numel(), dtype=torch.long, device=device)
    x_dict = {"bus": x_bus, "gen": x_gen}
    edge_index_dict = {
        ("bus", "connects", "bus"): edge_bus,
        ("gen", "connected_to", "bus"): torch.stack([gi, gen_bus], dim=0),
        ("bus", "connected_to", "gen"): torch.stack([gen_bus, gi], dim=0),
    }
    edge_attr_dict = {("bus", "connects", "bus"): edge_attr_bus}
    return x_dict, edge_index_dict, edge_attr_dict


def gridfm_branch_edges(batch, device, feature_transform="signed_log"):
    """Branch edges for GridFM, derived from the batch Y-bus off-diagonals."""
    from train_valid_test_gridfm import signed_log1p

    Y = batch["Ybus"].squeeze(0)
    idx = (Y.abs() > 0).nonzero(as_tuple=False)
    mask = idx[:, 0] != idx[:, 1]
    idx = idx[mask]
    ei = idx.t().to(device)
    y = Y[idx[:, 0], idx[:, 1]]
    attr = torch.stack([y.real.float(), y.imag.float()], dim=-1).to(device)
    if feature_transform == "signed_log":
        attr = signed_log1p(attr)
    return ei, attr
